### ISSUE TITLE
Consider appropriate logging

### ISSUE THREAD

**Issue by jonc125** [UCL-CloudLabs/user-portal#20]
And, in due course, automatically alerting us (e.g. on Slack, via Opbeat) when there are issues.

**Comment by ageorgou** [comment]
If needed for future reference, logging with Celery is tricky because Celery hijacks the root logger. Some info and discussion [here](https://groups.google.com/forum/#!topic/celery-users/xNPYTobJ5Rg/discussion), in Celery's GitHub issues([link](https://github.com/celery/celery/issues/3428), [link](https://github.com/celery/celery/issues/2509), [link](https://github.com/celery/celery/issues/1867)) and in [docs](http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-worker_hijack_root_logger).

**Comment by ageorgou** [comment]
Closed in #70.
